"""Draw the custom-CNN (Approach 1) architecture diagram.

The figure is generated by *introspecting* ``EncoderClassifier`` (a forward trace
records the tensor shape after every layer), so it can never drift from the code.
The conv trunk + FC bottleneck are shaded to mark the block that warm-starts from
the trained autoencoder's encoder (direct ``state_dict`` key match).

Run:
    PYTHONPATH=. /usr/local/bin/python3.8 -m bowhead.models.plot_architecture \
        --out docs/cnn_architecture.png
"""

from __future__ import annotations

import argparse
from pathlib import Path

import torch
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch

from bowhead.models.custom_cnn import EncoderClassifier

# Palette (colour-blind friendly-ish).
C_INPUT = "#cfd8dc"
C_CONV = ["#a8d5e2", "#7cb6cf", "#4f97bc"]   # 3 conv stages, deepening blue
C_FC = "#f4c89a"
C_LATENT = "#e07a5f"
C_HEAD = "#b5c99a"
C_WARM = "#fff3cd"


def trace_shapes(model: EncoderClassifier, hw: tuple[int, int]) -> dict:
    """Forward-trace and collect the shapes the diagram annotates."""
    x = torch.zeros(1, 1, *hw)
    shapes = {"input": tuple(x.shape[1:])}
    h = x
    conv_out = []
    enc = model.encoder.encoder
    for i, layer in enumerate(enc):
        h = layer(h)
        if isinstance(layer, torch.nn.MaxPool2d):
            conv_out.append(tuple(h.shape[1:]))  # (C, H, W) after each pool
    shapes["conv"] = conv_out
    shapes["flat"] = int(torch.flatten(h, 1).shape[1])
    lat = model.encoder.to_latent
    shapes["fc_hidden"] = lat[0].out_features
    shapes["latent"] = lat[-1].out_features
    shapes["num_classes"] = model.classifier[-1].out_features
    return shapes


def _box(ax, x, y, w, h, color, label, fontsize=8, ec="#37474f"):
    ax.add_patch(FancyBboxPatch(
        (x, y), w, h, boxstyle="round,pad=0.02,rounding_size=0.06",
        linewidth=1.1, edgecolor=ec, facecolor=color, zorder=3))
    ax.text(x + w / 2, y + h / 2, label, ha="center", va="center",
            fontsize=fontsize, zorder=4)


def _arrow(ax, x0, x1, y):
    ax.add_patch(FancyArrowPatch(
        (x0, y), (x1, y), arrowstyle="-|>", mutation_scale=12,
        linewidth=1.1, color="#546e7a", zorder=2))


def draw(model: EncoderClassifier, hw: tuple[int, int], out: Path) -> None:
    s = trace_shapes(model, hw)
    fig, ax = plt.subplots(figsize=(14, 4.6))
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 32)
    ax.axis("off")

    yc = 16          # vertical centre
    cursor = 2.0     # left edge of next block

    def place(w, h, color, top, sub, fs=8):
        nonlocal cursor
        y = yc - h / 2
        _box(ax, cursor, y, w, h, color, top, fontsize=fs)
        if sub:
            ax.text(cursor + w / 2, y - 1.6, sub, ha="center", va="top",
                    fontsize=7, color="#37474f")
        c0, c1 = cursor, cursor + w
        cursor = c1 + 2.4
        return c0, c1, y, y + h

    # Input spectrogram
    c, hh, ww = s["input"]
    _, x1, *_ = place(7, 12, C_INPUT, "Input\nspectrogram",
                      f"{c}×{hh}×{ww}\n(0-500 Hz, 3 s)")

    warm_x0 = cursor - 1.2  # start of the warm-started region

    # 3 conv blocks
    for i, (ch, ph, pw) in enumerate(s["conv"]):
        _arrow(ax, x1, cursor, yc)
        height = 8 + i * 4
        top = f"Conv 3×3\n→ {ch} ch\nBN · ReLU\nMaxPool 2"
        _, x1, *_ = place(8.5, height, C_CONV[i], top, f"{ch}×{ph}×{pw}", fs=7)

    # Flatten
    _arrow(ax, x1, cursor, yc)
    _, x1, *_ = place(4.5, 6, "#eceff1", "Flatten", f"{s['flat']:,}")

    # FC bottleneck (to_latent): Linear -> ReLU -> Linear
    _arrow(ax, x1, cursor, yc)
    _, x1, *_ = place(7, 9, C_FC, f"FC {s['flat']:,}\n→ {s['fc_hidden']}\nReLU\n→ {s['latent']}",
                      "to_latent", fs=7)

    warm_x1 = cursor - 2.4  # end of warm-started region

    # Latent vector
    _arrow(ax, x1, cursor, yc)
    _, x1, *_ = place(4.5, 11, C_LATENT, f"Latent\nz ∈ ℝ^{s['latent']}",
                      "32-D embedding", fs=8)

    # Classification head
    _arrow(ax, x1, cursor, yc)
    _, x1, *_ = place(7, 8, C_HEAD,
                      f"Linear\n{s['latent']} → {s['num_classes']}\nsoftmax",
                      "classification head", fs=7)

    # Output
    _arrow(ax, x1, cursor, yc)
    place(7, 8, C_INPUT, "Call\nprobability", "P(call) ∈ [0,1]")

    # Warm-start shaded bracket over conv trunk + to_latent
    ax.add_patch(FancyBboxPatch(
        (warm_x0, yc - 13.5), warm_x1 - warm_x0, 27,
        boxstyle="round,pad=0.1,rounding_size=0.2",
        linewidth=1.3, edgecolor="#d4a017", facecolor=C_WARM,
        alpha=0.28, zorder=1, linestyle="--"))
    ax.text((warm_x0 + warm_x1) / 2, yc + 13.6,
            "encoder trunk + FC bottleneck — warm-started from the trained "
            "autoencoder (state_dict key-matched)",
            ha="center", va="bottom", fontsize=8.5, style="italic",
            color="#8a6d00")

    n_params = sum(p.numel() for p in model.parameters())
    fig.suptitle("Custom CNN detector — AE-mirroring encoder + softmax head "
                 f"({n_params:,} parameters)", fontsize=12, y=1.02)
    ax.text(50, 0.5,
            "Mirrors the 32-D convolutional autoencoder's encoder path "
            "(3× Conv-BN-ReLU-MaxPool, 32→64→128; FC 24,960→64→32) so the "
            "unsupervised features transfer directly. Trained end-to-end with "
            "cross-entropy.",
            ha="center", va="bottom", fontsize=7.5, color="#455a64")

    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=200, bbox_inches="tight")
    svg = out.with_suffix(".svg")
    fig.savefig(svg, bbox_inches="tight")
    plt.close(fig)
    print(f"Wrote {out} and {svg}")


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Plot the custom-CNN architecture")
    p.add_argument("--out", type=Path, default=Path("docs/cnn_architecture.png"))
    p.add_argument("--height", type=int, default=121)
    p.add_argument("--width", type=int, default=104)
    return p.parse_args()


if __name__ == "__main__":
    a = _parse_args()
    model = EncoderClassifier(input_hw=(a.height, a.width))
    draw(model, (a.height, a.width), a.out)
